version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/acm"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/cloudfront"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/gaming_prod_us_west_2/on_demand"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/gaming_prod_us_west_2/spot"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/iam"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/cloudfront_s3_website"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/s3_bucket"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/vpc"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/route53"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/s3"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/vpc_prod_us_west_2"
    schedule:
      interval: "daily"
