pre_commit_task:
  container:
    image: carterjones/ci-runner:latest
  script: pre-commit run --all

terraform_lint_task:
  container:
    image: carterjones/ci-runner:latest
  env:
    AWS_ACCESS_KEY_ID: ENCRYPTED[73ceebbef19b3c80be9514ced179858a6a440781ac3c952546a0c175eac791a2ca5768070ff831c65316661431a854a7]
    AWS_SECRET_ACCESS_KEY: ENCRYPTED[55558071059f7d8fed267aba5e4050c7ed80f2067512465a2ae4a2df84a9989a35cef7a43eaf9affa94e79845c1f3d3f]
  script: cd terraform && ./lint.sh

docker_builder:
  depends_on: pre_commit
  env:
    DOCKERHUB_USERNAME: ENCRYPTED[5018190c06b59a297e862063ddf1c6d782a19b2beacc397754d891ee3bcdd958e2bd50b84774041a61f65cecc3555693]
    DOCKERHUB_PASSWORD: ENCRYPTED[28092cc5b56c798bbbcd40bf73ebd7278135c10ba59c8a4f8653a5f4767be365e6e6e69dc2551f0102ef5c494f466345]
    matrix:
      - NAME: ci-runner
      - NAME: arch
      - NAME: centos-7
      - NAME: centos-8
      - NAME: manjaro
      - NAME: ubuntu-20.04
  matrix:
    - name: build ${NAME} (and push when on main branch)
      script: cd docker && ./release.sh ${NAME}
