exclude: ^attic/.*$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.12
  hooks:
    - id: shellcheck
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.50.0
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
    - id: terraform_tfsec
