language: shell
dist: bionic
os: linux

services:
  - docker

before_install:
  # Change to a workspace to avoid interferance with this repo's files/directories.
  - pushd $(mktemp -d)

  # Install tflint.
  - curl -L "$(curl -Ls https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" -o tflint.zip
  - unzip tflint.zip
  - sudo mv tflint /usr/local/bin/

  # Install Terraform.
  - curl -o terraform.zip https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip
  - unzip -o terraform.zip
  - sudo mv -f terraform /usr/local/bin/

  # Change back to the original directory.
  - popd

jobs:
  include:
    - stage: lint
      script: cd terraform && ./lint.sh
    - stage: build docker images (and push on main)
      script: cd docker && ./release.sh arch
      env: TARGET=arch
    - script: cd docker && ./release.sh centos-7
      env: TARGET=centos-7
    - script: cd docker && ./release.sh centos-8
      env: TARGET=centos-8
    - script: cd docker && ./release.sh manjaro
      env: TARGET=manjaro
    - script: cd docker && ./release.sh ubuntu-18.04
      env: TARGET=ubuntu-18.04
    - script: cd docker && ./release.sh ubuntu-20.04
      env: TARGET=ubuntu-20.04
