sudo: required

services:
  - docker

jobs:
  include:
    - stage: Build and push images
      script: cd docker/arch && ./release.sh
      env: TARGET=Arch
    - script: cd docker/infra-builder && ./release.sh
      env: TARGET=Infra Builder
    - script: cd docker/manjaro && ./release.sh
      env: TARGET=Manjaro
    - script: cd docker/ubuntu-14.04 && ./release.sh
      env: TARGET=Ubuntu 14.04
    - script: cd docker/ubuntu-16.04 && ./release.sh
      env: TARGET=Ubuntu 16.04
    - script: cd docker/ubuntu-18.04 && ./release.sh
      env: TARGET=Ubuntu 18.04
