sudo: required

services:
  - docker

jobs:
  include:
    - stage: Build and push images
      script: cd docker/arch && ./release.sh
      env: OS=Arch
    - script: cd docker/manjaro && ./release.sh
      env: OS=Manjaro
    - script: cd docker/ubuntu-14.04 && ./release.sh
      env: OS=Ubuntu 14.04
    - script: cd docker/ubuntu-16.04 && ./release.sh
      env: OS=Ubuntu 16.04
    - script: cd docker/ubuntu-18.04 && ./release.sh
      env: OS=Ubuntu 18.04
