language: shell
dist: bionic
os: linux

services:
  - docker

jobs:
  include:
    - stage: Build and push images
      script: cd docker/arch && ./release.sh
      env: TARGET=arch
    - script: cd docker/centos-7 && ./release.sh
      env: TARGET=centos-7
    - script: cd docker/centos-8 && ./release.sh
      env: TARGET=centos-8
    - script: cd docker/manjaro && ./release.sh
      env: TARGET=manjaro
    - script: cd docker/ubuntu-18.04 && ./release.sh
      env: TARGET=ubuntu-18.04
    - script: cd docker/ubuntu-20.04 && ./release.sh
      env: TARGET=ubuntu-20.04
