language: shell
dist: bionic
os: linux

services:
  - docker

jobs:
  include:
    - stage: Build and push images
      script: cd docker && ./release.sh arch
      env: TARGET=arch
    - script: cd docker && ./release.sh centos-7
      env: TARGET=centos-7
    - script: cd docker && ./release.sh centos-8
      env: TARGET=centos-8
    - script: cd docker && ./release.sh manjaro
      env: TARGET=manjaro
    - script: cd docker && ./release.sh ubuntu-18.04
      env: TARGET=ubuntu-18.04
    - script: cd docker && ./release.sh ubuntu-20.04
      env: TARGET=ubuntu-20.04
