sudo: required

services:
  - docker

jobs:
  include:
    - stage: Build and push images
      script: cd docker/arch && ./release.sh
      env: TARGET=Arch
    - script: cd docker/infra-builder && ./release.sh
      env: TARGET=Infra_Builder
    - script: cd docker/centos-7 && ./release.sh
      env: TARGET=CentOS_7
    - script: cd docker/manjaro && ./release.sh
      env: TARGET=Manjaro
    - script: cd docker/rpm-builder && ./release.sh
      env: TARGET=RPM_Builder
    - script: cd docker/ubuntu-14.04 && ./release.sh
      env: TARGET=Ubuntu_14.04
    - script: cd docker/ubuntu-16.04 && ./release.sh
      env: TARGET=Ubuntu_16.04
    - script: cd docker/ubuntu-18.04 && ./release.sh
      env: TARGET=Ubuntu_18.04
    - script: cd docker/ubuntu-18.10 && ./release.sh
      env: TARGET=Ubuntu_18.10
