resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/carterjones/infrastructure
      branch: f/hax

jobs:
  - name: build-concourse
    plan:
      - get: repo
#        trigger: true
      - task: build
        file: repo/ci/build/concourse.yml

  - name: build-git
    plan:
      - get: repo
#        trigger: true
      - task: build
        file: repo/ci/build/git.yml
