version: 2
jobs:
  arch:
    docker:
      - image: docker:18
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Arch
          command: |
            cd docker/arch
            docker build -f Dockerfile -t carterjones/arch:latest .
            docker tag carterjones/arch:latest "carterjones/arch:${CIRCLE_SHA1}"
            docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_PASSWORD}"
            docker push "carterjones/arch:${CIRCLE_SHA1}"
            docker push "carterjones/arch:latest"
  manjaro:
    docker:
      - image: docker:18
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Manjaro
          command: |
            cd docker/manjaro
            docker build -f Dockerfile -t carterjones/manjaro:latest .
            docker tag carterjones/manjaro:latest "carterjones/manjaro:${CIRCLE_SHA1}"
            docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_PASSWORD}"
            docker push "carterjones/manjaro:${CIRCLE_SHA1}"
            docker push "carterjones/manjaro:latest"
  infra-builder:
    docker:
      - image: docker:18
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push infra-builder
          command: |
            cd docker/infra-builder
            docker build -f Dockerfile -t carterjones/infra-builder:latest .
            docker tag carterjones/infra-builder:latest "carterjones/infra-builder:${CIRCLE_SHA1}"
            docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_PASSWORD}"
            docker push "carterjones/infra-builder:${CIRCLE_SHA1}"
            docker push "carterjones/infra-builder:latest"
  ubuntu-14.04:
    docker:
      - image: docker:18
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Ubuntu 14.04
          command: |
            cd docker/ubuntu-14.04
            docker build -f Dockerfile -t carterjones/ubuntu-14.04:latest .
            docker tag carterjones/ubuntu-14.04:latest "carterjones/ubuntu-14.04:${CIRCLE_SHA1}"
            docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_PASSWORD}"
            docker push "carterjones/ubuntu-14.04:${CIRCLE_SHA1}"
            docker push "carterjones/ubuntu-14.04:latest"
  ubuntu-16.04:
    docker:
      - image: docker:18
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Ubuntu 16.04
          command: |
            cd docker/ubuntu-16.04
            docker build -f Dockerfile -t carterjones/ubuntu-16.04:latest .
            docker tag carterjones/ubuntu-16.04:latest "carterjones/ubuntu-16.04:${CIRCLE_SHA1}"
            docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_PASSWORD}"
            docker push "carterjones/ubuntu-16.04:${CIRCLE_SHA1}"
            docker push "carterjones/ubuntu-16.04:latest"
  ubuntu-18.04:
    docker:
      - image: docker:18
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Ubuntu 18.04
          command: |
            cd docker/ubuntu-18.04
            docker build -f Dockerfile -t carterjones/ubuntu-18.04:latest .
            docker tag carterjones/ubuntu-18.04:latest "carterjones/ubuntu-18.04:${CIRCLE_SHA1}"
            docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_PASSWORD}"
            docker push "carterjones/ubuntu-18.04:${CIRCLE_SHA1}"
            docker push "carterjones/ubuntu-18.04:latest"

workflows:
  version: 2
  always:
    jobs:
      - arch
      - manjaro
      - infra-builder
      - ubuntu-14.04
      - ubuntu-16.04
      - ubuntu-18.04
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - arch
      - manjaro
      - infra-builder
      - ubuntu-14.04
      - ubuntu-16.04
      - ubuntu-18.04
