FROM ubuntu:18.04

RUN apt-get update && apt-get install -y locales sudo && \
    rm -rf /var/lib/apt/lists/* && \
    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

RUN /bin/bash -c "echo notroot ALL=\(ALL\) NOPASSWD: ALL >> /etc/sudoers"
RUN useradd -ms /bin/bash notroot
USER notroot
