FROM manjarolinux/base:latest

RUN pacman -Syu --noconfirm \
    git \
    grep \
    sed \
    sudo

RUN /bin/bash -c "echo notroot ALL=\(ALL\) NOPASSWD: ALL >> /etc/sudoers"
RUN useradd -ms /bin/bash notroot
USER notroot
