$migrate_files_and_scripts = <<SCRIPT
cp -r /vagrant/files /tmp
cp -r /vagrant/scripts /tmp
SCRIPT

$cleanup = <<SCRIPT
sudo apt-get -y autoremove
sudo apt-get -y clean
sync
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "carterjones/base"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end

  config.vm.synced_folder "../../", "/home/vagrant/infrastructure"
  config.vm.provision "file", source: "~/.aws/", destination: "/home/vagrant/.aws/credentials"
  config.vm.provision "file", source: "~/.gitconfig", destination: "/home/vagrant/.gitconfig"

  # This tries to mimic template.json's logic.
  config.vm.provision "shell", inline: $migrate_files_and_scripts
  config.vm.provision "shell", inline: "/bin/bash /vagrant/pack.sh"
  config.vm.provision "shell", inline: $cleanup

end
