resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/carterjones/infrastructure
      branch: master

  - name: weekly
    type: time
    source:
      start: 7:00 AM
      stop: 9:00 AM
      days: [Saturday]

  - name: base-rc
    type: s3
    source:
      bucket: carterjones-pipeline-artifacts
      versioned_file: base/ami-rc
      region_name: us-west-2
      private: true
      access_key_id: {{concourse_access_key}}
      secret_access_key: {{concourse_secret_key}}

  - name: test-instance-data
    type: s3
    source:
      bucket: carterjones-pipeline-artifacts
      versioned_file: base/test-instance-data.tar.gz
      region_name: us-west-2
      private: true
      access_key_id: {{concourse_access_key}}
      secret_access_key: {{concourse_secret_key}}

  - name: base-final
    type: s3
    source:
      bucket: carterjones-pipeline-artifacts
      versioned_file: base/ami
      region_name: us-west-2
      private: true
      access_key_id: {{concourse_access_key}}
      secret_access_key: {{concourse_secret_key}}

jobs:
  - name: build-weekly
    plan:
      - aggregate:
          - get: repo
          - get: weekly
            trigger: true
      - task: build
        file: repo/ci/build/base.yml
      - put: base-rc
        params:
          file: ami/id

  - name: build-manual
    plan:
      - get: repo
      - task: build
        file: repo/ci/build/base.yml
      - put: base-rc
        params:
          file: ami/id

  - name: launch-test-instance
    plan:
      - get: repo
      - get: ami-in
        resource: base-rc
        trigger: true
      - task: test
        file: repo/ci/tasks/launch-test-instance.yml
        params:
          ROLE: base
          TIER: ci
      - put: test-instance-data
        params:
          file: test-instance/data.tar.gz

  - name: test-login
    plan:
      - get: repo
      - get: ami-in
        resource: base-rc
      - get: test-instance
        resource: test-instance-data
        passed: [launch-test-instance]
        trigger: true
      - task: test
        file: repo/ci/tasks/ssh-login.yml
        params:
          ROLE: base
          TIER: ci

  - name: tag-ami
    plan:
      - get: repo
      - get: ami-in
        resource: base-rc
        passed: [test-login]
        trigger: true
      - task: tag-ami
        file: repo/ci/tasks/tag-ami.yml
      - put: base-final
        params:
          file: ami-out/id

  - name: destroy-test-instance
    plan:
      - get: repo
        passed: [test-login]
        trigger: true
      - task: destroy-test-instance
        file: repo/ci/tasks/destroy-instance.yml
        params:
          ROLE: base
          TIER: ci
