resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/carterjones/infrastructure
      branch: master

  - name: weekly
    type: time
    source:
      start: 9:00 AM
      stop: 12:00 PM
      days: [Saturday]

jobs:
  - name: build-weekly
    plan:
      - aggregate:
          - get: repo
            trigger: true
          - get: weekly
            trigger: true
      - task: build
        file: repo/ci/build/concourse.yml
