resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/carterjones/infrastructure
      branch: f/hax

  - name: weekly
    type: time
    source:
      start: 9:00 AM
      stop: 12:00 PM
      days: [Saturday]

  - name: blog-rc
    type: s3
    source:
      bucket: carterjones-pipeline-artifacts
      versioned_file: blog/ami-rc
      region_name: us-west-2
      private: true
      access_key_id: {{concourse_access_key}}
      secret_access_key: {{concourse_secret_key}}

  - name: blog-final
    type: s3
    source:
      bucket: carterjones-pipeline-artifacts
      versioned_file: blog/ami
      region_name: us-west-2
      private: true
      access_key_id: {{concourse_access_key}}
      secret_access_key: {{concourse_secret_key}}

  - name: base-final
    type: s3
    source:
      bucket: carterjones-pipeline-artifacts
      versioned_file: base/ami
      region_name: us-west-2
      private: true
      access_key_id: {{concourse_access_key}}
      secret_access_key: {{concourse_secret_key}}

jobs:
  - name: build-weekly
    plan:
      - aggregate:
          - get: repo
            trigger: true
          - get: weekly
            trigger: true
      - task: build
        file: repo/ci/build/blog.yml
      - put: blog-rc
        params:
          file: ami/id

  # Note: this simply detects that a new version of base has been built. It does
  # not actually import the base AMI from this resource. Terraform automatically
  # grabs the latest base AMI instead.
  - name: build-from-base-change
    plan:
      - aggregate:
          - get: repo
          - get: base-final
            trigger: true
      - task: build
        file: repo/ci/build/blog.yml
      - put: blog-rc
        params:
          file: ami/id

  - name: build-manual
    plan:
      - get: repo
      - task: build
        file: repo/ci/build/blog.yml
      - put: blog-rc
        params:
          file: ami/id

  - name: test-login
    plan:
      - get: repo
      - get: ami-in
        resource: blog-rc
        # passed:
        #   - build-weekly
        #   - build-from-base-change
        #   - build-manual
        trigger: true
      - task: test
        file: repo/ci/test/ssh-login.yml
        params:
          ROLE: blog
          TIER: ci
      - put: blog-final
        params:
          file: ami-out/id

# TODO: add ebs volume snapshot
# TODO: add deployoment job
# TODO: add some type of notification of success/failure
