resources:
  - name: repo
    type: git
    source:
      uri: git@git.carterjones.info:personal/trading.git
      branch: f/app
      private_key: {{private_git_server_key}}

  - name: release
    type: s3
    source:
      bucket: carterjones-pipeline-artifacts
      versioned_file: trading/bundle.tar.gz
      region_name: us-west-2
      private: true
      access_key_id: {{concourse_access_key}}
      secret_access_key: {{concourse_secret_key}}

jobs:
  - name: build
    plan:
      - get: repo
        trigger: yes
      - task: build
        file: repo/ci/build/trading.yml
      - put: release
        params:
          file: out/bundle.tar.gz
