resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/carterjones/infrastructure
      branch: master

  - name: weekly
    type: time
    source:
      start: 9:00 AM
      stop: 12:00 PM
      days: [Saturday]

jobs:
  - name: build
    plan:
      - aggregate:
          - get: repo
          - get: weekly
            trigger: true
      - task: build
        file: repo/ci/build/git.yml

# TODO: add ebs volume snapshot
# TODO: add deployoment job
# TODO: add some type of notification of success/failure
